<?php

namespace AppBundle\Entity\Repository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll(){
        return $this->getEntityManager()
            ->createQuery('SELECT r, CASE WHEN r.status = 0 THEN 1 ELSE 0 END AS HIDDEN pendingStatus  
                FROM AppBundle:Order r ORDER BY pendingStatus DESC, r.status DESC')
            ->getArrayResult();
    }
}
