<?php

namespace AppBundle\Entity\Repository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll(){
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM AppBundle:Order r ORDER BY r.status = 0')
            ->getArrayResult();
    }
}
